### ISSUE TITLE
UTF-8 support 

### ISSUE THREAD

**Issue by kastony** [secrethash/trickster#3]
Hi,
Truncator, Slug Converter doesn't work with Greek characters, It would be nice to add utf-8 support.

Thanks in advance

**Comment by secrethash** [comment]
### There are certain things that are needed to look through for this issue (if you are still facing).

First of all `sorry` for the late reply. Secondly, if you are still facing this problem, this is due to your 
***php server/database (if you are grabbing the data from your database)/Web Browser/Code Editor or IDE.***

> `Slug` eliminates the special characters so that the url is search engine friendly. Keeping the special characters in your url is not at all a good practice.

Optionally, you can try this to solve your problem:
```php
<?php
     header('Content-type: text/plain; charset=utf-8');
 ?>
```
it will send a header request to the browser to support the UTF-8 Encoding.

Also for a further reading, you can go through this: [How to setup your PHP site to use UTF-8](https://allseeing-i.com/How-to-setup-your-PHP-site-to-use-UTF8).
